apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafkaui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jouw-org/jouw-repo.git'
    targetRevision: main
    path: kafkaui
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kafka-ui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
