apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kafka-ui
    repo: https://provectus.github.io/kafka-ui-charts
    version: 0.7.1   # of de laatste versie uit de repo
    releaseName: kafka-ui
    namespace: kafka
    valuesInline:
      envs:
        config:
          KAFKA_CLUSTERS_0_NAME: local
          KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: my-cluster-kafka-bootstrap.kafka:9092
